import type { SportConfig } from './schema.js';

const MINUTES = 60_000;

/**
 * Football (Soccer). Basic + Advanced tiers per the brief.
 *
 * `clean sheet` from the brief is a DERIVED concept (opponent scored 0) rather than a recordable
 * event — it is computed in the team/career stat layer, since it depends on the opposing side's
 * tally which a single-entity formula can't see. Everything else here is a first-class event type.
 */
export const footballConfig: SportConfig = {
  sport: 'FOOTBALL',
  version: 1,
  name: 'Football',
  periods: {
    regulationCount: 2,
    periodLabel: 'Half',
    periodLengthMs: 45 * MINUTES,
    allowsExtraTime: true,
    extraTimeCount: 2,
    extraTimeLengthMs: 15 * MINUTES,
    tiebreak: 'PENALTIES',
    pointsToWinPeriod: 0,
    winByTwo: false,
  },
  clock: {
    direction: 'UP',
    countsStoppage: true,
    enabled: true,
  },
  eventTypes: [
    // ── Basic ──────────────────────────────────────────────────────────────
    {
      id: 'goal',
      label: 'Goal',
      shortLabel: 'Goal',
      tier: 'BASIC',
      icon: 'goal',
      requiresPlayer: true,
      score: { side: 'SAME', points: 1 },
      intent: 'positive',
      chains: [
        {
          id: 'goal_assist',
          title: 'Who assisted?',
          recordsEventType: 'assist',
          optional: true,
          side: 'SAME',
        },
      ],
    },
    {
      id: 'assist',
      label: 'Assist',
      tier: 'BASIC',
      icon: 'assist',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
    {
      id: 'own_goal',
      label: 'Own Goal',
      shortLabel: 'OG',
      tier: 'BASIC',
      icon: 'own-goal',
      requiresPlayer: true,
      score: { side: 'OPPONENT', points: 1 },
      intent: 'negative',
      chains: [],
    },
    {
      id: 'yellow_card',
      label: 'Yellow Card',
      shortLabel: 'YC',
      tier: 'BASIC',
      icon: 'yellow-card',
      requiresPlayer: true,
      intent: 'negative',
      chains: [],
    },
    {
      id: 'red_card',
      label: 'Red Card',
      shortLabel: 'RC',
      tier: 'BASIC',
      icon: 'red-card',
      requiresPlayer: true,
      intent: 'negative',
      chains: [],
    },
    {
      id: 'substitution',
      label: 'Substitution',
      shortLabel: 'Sub',
      tier: 'BASIC',
      icon: 'substitution',
      requiresPlayer: true,
      intent: 'neutral',
      chains: [],
    },
    // ── Advanced ───────────────────────────────────────────────────────────
    {
      id: 'shot',
      label: 'Shot',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'neutral',
      chains: [],
    },
    {
      id: 'shot_on_target',
      label: 'Shot on Target',
      shortLabel: 'SoT',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
    {
      id: 'woodwork',
      label: 'Hit Woodwork',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'neutral',
      chains: [],
    },
    {
      id: 'big_chance_missed',
      label: 'Big Chance Missed',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'negative',
      chains: [],
    },
    {
      id: 'dribble',
      label: 'Dribble',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
    {
      id: 'interception',
      label: 'Interception',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
    {
      id: 'save',
      label: 'Save',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
    {
      id: 'foul',
      label: 'Foul',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'negative',
      chains: [],
    },
    {
      id: 'corner',
      label: 'Corner',
      tier: 'ADVANCED',
      requiresPlayer: false,
      intent: 'neutral',
      chains: [],
    },
    {
      id: 'offside',
      label: 'Offside',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'negative',
      chains: [],
    },
    {
      id: 'penalty_won',
      label: 'Penalty Won',
      tier: 'ADVANCED',
      requiresPlayer: true,
      intent: 'positive',
      chains: [],
    },
  ],
  derivedStats: [
    {
      key: 'shot_accuracy',
      label: 'Shot Accuracy',
      format: 'percent',
      scope: 'player',
      expr: 'shot_on_target / shot * 100',
      tiers: ['ADVANCED'],
    },
    {
      key: 'goal_conversion',
      label: 'Conversion',
      format: 'percent',
      scope: 'player',
      expr: 'goal / shot * 100',
      tiers: ['ADVANCED'],
    },
  ],
  playerStatColumns: [
    'goal',
    'assist',
    'shot',
    'shot_on_target',
    'save',
    'yellow_card',
    'red_card',
    'foul',
  ],
  buttonLayout: {
    BASIC: [
      { id: 'scoring', label: 'Scoring', eventTypeIds: ['goal', 'own_goal'] },
      { id: 'playmaking', label: 'Playmaking', eventTypeIds: ['assist'] },
      { id: 'discipline', label: 'Discipline', eventTypeIds: ['yellow_card', 'red_card'] },
      { id: 'bench', label: 'Bench', eventTypeIds: ['substitution'] },
    ],
    ADVANCED: [
      { id: 'scoring', label: 'Scoring', eventTypeIds: ['goal', 'own_goal'] },
      { id: 'playmaking', label: 'Playmaking', eventTypeIds: ['assist'] },
      {
        id: 'shooting',
        label: 'Shooting',
        eventTypeIds: ['shot', 'shot_on_target', 'woodwork', 'big_chance_missed'],
      },
      { id: 'defending', label: 'Defending', eventTypeIds: ['interception', 'save', 'offside'] },
      { id: 'duels', label: 'Duels', eventTypeIds: ['dribble', 'foul'] },
      { id: 'set_pieces', label: 'Set Pieces', eventTypeIds: ['corner', 'penalty_won'] },
      { id: 'discipline', label: 'Discipline', eventTypeIds: ['yellow_card', 'red_card'] },
      { id: 'bench', label: 'Bench', eventTypeIds: ['substitution'] },
    ],
  },
};
